-- PostgreSQL Production Database Schema for TalentCraft HR Consultancy Digital Operations Platform
-- Generated by BizzMitra AI Engine

CREATE TABLE IF NOT EXISTS public.work_orders (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  priority TEXT NOT NULL CHECK (priority IN ('Critical', 'High', 'Medium', 'Low')),
  status TEXT NOT NULL CHECK (status IN ('Intake', 'In Progress', 'Review', 'Completed')),
  assignee TEXT NOT NULL,
  impact_score INT DEFAULT 90,
  sla_days INT DEFAULT 3,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.work_orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read-write for demo application"
  ON public.work_orders
  FOR ALL
  USING (true)
  WITH CHECK (true);
